const $ = id => document.getElementById(id);
const t = document.body.dataset.tool;

function run() {
  const v = $('input1')?.value || '';
  const v2 = $('input2')?.value || '';
  const o = $('out');
  if (!o) return;
  try {
    if (t === 'csv-to-json') {
      const rows = v.trim().split(/\r?\n/).map(x => x.split(','));
      o.textContent = JSON.stringify(rows.slice(1).map(a => Object.fromEntries(rows[0].map((h,i) => [h.trim(), (a[i] || '').trim()]))), null, 2);
    } else if (t === 'json-to-csv') {
      const a = JSON.parse(v), h = [...new Set(a.flatMap(x => Object.keys(x)))];
      o.textContent = h.join(',') + '\n' + a.map(x => h.map(k => JSON.stringify(x[k] ?? '')).join(',')).join('\n');
    } else if (['xml-formatter','html-formatter'].includes(t)) o.textContent = v.replace(/></g, '>\n<');
    else if (['css-minifier','js-minifier'].includes(t)) o.textContent = v.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\s+/g,' ').replace(/\s*([{}:;,])\s*/g,'$1').trim();
    else if (t === 'html-encoder') o.textContent = v.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;');
    else if (t === 'html-decoder') { const x = document.createElement('textarea'); x.innerHTML = v; o.textContent = x.value; }
    else if (t === 'uuid-generator') o.textContent = Array.from({length: +v || 1}, () => crypto.randomUUID()).join('\n');
    else if (t === 'slug-generator') o.textContent = v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
    else if (t === 'lorem-ipsum') o.textContent = Array.from({length: +v || 3}, () => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.').join('\n\n');
    else if (t === 'remove-duplicate-lines') o.textContent = [...new Set(v.split(/\r?\n/))].join('\n');
    else if (t === 'sort-lines') o.textContent = v.split(/\r?\n/).filter(Boolean).sort((a,b) => a.localeCompare(b)).join('\n');
    else if (t === 'text-cleaner') o.textContent = v.split(/\r?\n/).map(x => x.trim().replace(/\s+/g,' ')).filter(Boolean).join('\n');
    else if (t === 'reading-time') o.textContent = `Perkiraan waktu membaca: ${Math.max(1, Math.ceil(v.trim().split(/\s+/).filter(Boolean).length / 200))} menit`;
    else if (t === 'typing-speed-test') o.textContent = `Kecepatan: ${Math.round(v.trim().split(/\s+/).filter(Boolean).length / ((+v2 || 60) / 60))} WPM`;
    else if (t === 'random-number-generator') { const min = +v || 1, max = +v2 || 100; o.textContent = Math.floor(Math.random() * (max-min+1)) + min; }
    else if (t === 'random-picker') { const a = v.split(/[,\n]/).map(x => x.trim()).filter(Boolean); o.textContent = a[Math.floor(Math.random()*a.length)] || ''; }
    else if (t === 'hex-to-rgb') { let h = v.replace('#',''); if(h.length===3) h=h.split('').map(x=>x+x).join(''); o.textContent=`rgb(${parseInt(h.slice(0,2),16)}, ${parseInt(h.slice(2,4),16)}, ${parseInt(h.slice(4,6),16)})`; }
    else if (t === 'rgb-to-hex') o.textContent = '#' + v.split(',').map(x => Math.max(0,Math.min(255,+x.trim()||0)).toString(16).padStart(2,'0')).join('');
    else if (['length-converter','weight-converter'].includes(t)) o.textContent = (+v * (+v2 || 1)).toString();
    else if (t === 'temperature-converter') { const x=+v; o.textContent=v2==='C-F'?x*9/5+32:v2==='F-C'?(x-32)*5/9:v2==='C-K'?x+273.15:x-273.15; }
    else if (t === 'time-duration-calculator') { const a=new Date('1970-01-01T'+v), b=new Date('1970-01-01T'+v2), m=Math.abs(b-a)/60000; o.textContent=`${Math.floor(m/60)} jam ${m%60} menit`; }
    else if (['loan-calculator','emi-calculator'].includes(t)) { const p=+v||0,r=(+v2||0)/1200,n=+(document.getElementById('input3')?.value||12),m=r?p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):p/n; o.textContent=`Cicilan per bulan: ${m.toFixed(2)}`; }
    else if (t === 'savings-calculator') { const m=+v||0,r=(+v2||0)/1200,n=+(document.getElementById('input3')?.value||12); o.textContent=`Nilai akhir: ${(m*((Math.pow(1+r,n)-1)/r||n)).toFixed(2)}`; }
    else if (t === 'tip-calculator') o.textContent=`Tip: ${((+v||0)*(+v2||0)/100).toFixed(2)} | Total: ${((+v||0)*(1+(+v2||0)/100)).toFixed(2)}`;
    else if (t === 'tax-calculator') o.textContent=`Pajak: ${((+v||0)*(+v2||0)/100).toFixed(2)}`;
    else if (t === 'compound-interest-calculator') { const p=+v||0,r=(+v2||0)/100,n=+(document.getElementById('input3')?.value||1); o.textContent=`Nilai akhir: ${(p*Math.pow(1+r,n)).toFixed(2)}`; }
    else if (t === 'simple-interest-calculator') { const p=+v||0,r=(+v2||0)/100,n=+(document.getElementById('input3')?.value||1); o.textContent=`Bunga: ${(p*r*n).toFixed(2)} | Total: ${(p*(1+r*n)).toFixed(2)}`; }
    else if (t === 'profit-margin-calculator') { const c=+v||0,s=+v2||0; o.textContent=`Margin: ${s?((s-c)/s*100).toFixed(2):0}%`; }
    else if (t === 'markup-calculator') o.textContent=`Harga jual: ${((+v||0)*(1+(+v2||0)/100)).toFixed(2)}`;
    else if (t === 'break-even-calculator') { const f=+v||0,p=+v2||0,c=+(document.getElementById('input3')?.value||0); o.textContent=`Titik impas: ${p>c?(f/(p-c)).toFixed(2):'—'} unit`; }
    else if (t === 'percentage-change-calculator') { const a=+v||0,b=+v2||0; o.textContent=`Perubahan: ${a?((b-a)/a*100).toFixed(2):0}%`; }
    else if (t === 'date-calculator') { const d=new Date(v); d.setDate(d.getDate()+(+v2||0)); o.textContent=isNaN(d)?'Tanggal tidak valid':d.toISOString().slice(0,10); }
    else if (t === 'countdown-timer') { const end=Date.now()+(+v||60)*1000,id=setInterval(()=>{const s=Math.max(0,Math.ceil((end-Date.now())/1000));o.textContent=s+' detik';if(!s)clearInterval(id);},200); }
    else if (t === 'stopwatch') { const st=Date.now(),id=setInterval(()=>o.textContent=((Date.now()-st)/1000).toFixed(1)+' detik',100); setTimeout(()=>clearInterval(id),3600000); }
    else if (t === 'invoice-generator') o.textContent=`INVOICE\n${v||'Nama pelanggan'}\n${v2||'Rp 0'}\n\nCetak halaman ini untuk menyimpan invoice.`;
    else o.textContent = 'Tool siap digunakan.';
  } catch(e) { o.textContent = 'Input belum valid.'; console.error(e); }
}

function img(mode) {
  const f=$('file')?.files[0]; if(!f) return;
  const im=new Image(); im.onload=()=>{ const c=document.createElement('canvas'); c.width=im.width;c.height=im.height;c.getContext('2d').drawImage(im,0,0); c.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='toolkita.'+(mode.split('/')[1]||'jpg');a.click();URL.revokeObjectURL(a.href);},mode,.9);}; im.src=URL.createObjectURL(f);
}
function resize() {
  const f=$('file')?.files[0],w=+$('input1')?.value; if(!f||!w)return;
  const im=new Image(); im.onload=()=>{const c=document.createElement('canvas'),h=Math.round(im.height*w/im.width);c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);c.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='resized.jpg';a.click();URL.revokeObjectURL(a.href);},'image/jpeg',.9);}; im.src=URL.createObjectURL(f);
}
function image64() { const f=$('file')?.files[0]; if(f){const r=new FileReader();r.onload=()=>{$('out').textContent=r.result};r.readAsDataURL(f);} }

// SEO content shared by all 50 tool pages. Content is selected by the page's data-tool value.
const seo = {
'jpg-to-png': ['JPG ke PNG Online Gratis','Konverter ini mengubah gambar JPG menjadi PNG langsung di browser. Cocok untuk kebutuhan desain, dokumentasi, dan file gambar yang membutuhkan format PNG.',['Pilih file JPG dari perangkat.','Klik tombol konversi.','Simpan file PNG yang dihasilkan.'],['Apakah file diunggah ke server?','Konversi dilakukan di browser sehingga file tidak perlu dikirim ke server ToolKita.','Apakah kualitas gambar tetap sama?','Konversi mempertahankan ukuran gambar, tetapi format PNG dapat menghasilkan ukuran file berbeda.']],
'png-to-jpg': ['PNG ke JPG Online Gratis','Ubah gambar PNG menjadi JPG dengan cepat tanpa aplikasi tambahan. Tool ini berguna saat sebuah platform membutuhkan format JPG.',['Pilih file PNG.','Klik tombol konversi JPG.','Download hasil konversi.'],['Kapan PNG perlu diubah ke JPG?','Saat membutuhkan format JPG untuk kompatibilitas atau ukuran file tertentu.','Apakah transparansi PNG tetap ada?','JPG tidak mendukung transparansi, sehingga area transparan akan menjadi latar saat dikonversi.']],
'webp-to-jpg': ['WebP ke JPG Online Gratis','Konversi gambar WebP menjadi JPG langsung dari browser untuk kebutuhan upload, desain, atau dokumentasi.',['Pilih file WebP.','Jalankan konversi.','Download JPG hasilnya.'],['Mengapa mengubah WebP ke JPG?','JPG didukung oleh banyak aplikasi dan layanan lama.','Apakah perlu install aplikasi?','Tidak, proses dilakukan langsung di browser.']],
'jpg-to-webp': ['JPG ke WebP Online Gratis','Ubah gambar JPG ke format WebP untuk penggunaan web dan kebutuhan file gambar modern.',['Pilih gambar JPG.','Klik tombol konversi WebP.','Simpan file WebP.'],['Apa kegunaan WebP?','WebP dirancang untuk gambar web dan dapat memberikan ukuran file yang efisien.','Apakah ukuran gambar berubah?','Dimensi gambar dipertahankan.']],
'png-to-webp': ['PNG ke WebP Online Gratis','Konversi PNG menjadi WebP langsung di browser untuk kebutuhan website dan optimasi aset gambar.',['Pilih file PNG.','Klik konversi WebP.','Download hasilnya.'],['Apakah WebP cocok untuk website?','WebP umum digunakan sebagai format gambar untuk website.','Apakah dimensi gambar berubah?','Dimensi dasar gambar dipertahankan saat konversi.']],
'webp-to-png': ['WebP ke PNG Online Gratis','Ubah WebP menjadi PNG untuk kebutuhan desain, editing, atau kompatibilitas aplikasi.',['Pilih file WebP.','Klik konversi PNG.','Simpan file PNG.'],['Mengapa memakai PNG?','PNG mendukung transparansi dan banyak aplikasi desain.','Apakah proses dilakukan online di server?','Pemrosesan dilakukan di browser pada perangkat pengguna.']],
'image-resizer': ['Image Resizer Online Gratis','Atur lebar gambar dengan cepat dan pertahankan rasio aspek agar gambar lebih mudah digunakan di website atau media sosial.',['Pilih gambar.','Masukkan lebar yang diinginkan.','Klik resize dan simpan hasil.'],['Apakah rasio gambar dipertahankan?','Ya, tinggi dihitung mengikuti rasio ukuran gambar asli.','Format hasilnya apa?','Tool menghasilkan file JPG.']],
'image-rotator': ['Image Rotator Online Gratis','Putar gambar untuk memperbaiki orientasi atau menyiapkan aset sebelum digunakan di dokumen dan website.',['Pilih gambar.','Pilih aksi rotasi yang tersedia.','Simpan gambar hasilnya.'],['Untuk apa rotasi gambar?','Untuk memperbaiki orientasi atau menyesuaikan tampilan gambar.','Apakah gambar asli berubah?','Tidak, hasil dibuat sebagai file baru.']],
'image-to-base64': ['Image ke Base64 Online Gratis','Ubah file gambar menjadi Data URL Base64 yang dapat digunakan pada HTML, CSS, atau kebutuhan pengembangan lainnya.',['Pilih file gambar.','Tunggu proses pembacaan file selesai.','Salin hasil Base64.'],['Apa itu Base64 gambar?','Base64 adalah representasi teks dari data biner gambar.','Apakah Base64 cocok untuk semua gambar?','Format Data URL dapat digunakan untuk berbagai format gambar yang didukung browser.']],
'base64-to-image': ['Base64 ke Image Online Gratis','Konversi Data URL Base64 kembali menjadi gambar untuk kebutuhan pengembangan dan pengujian.',['Tempel Data URL Base64.','Jalankan konversi.','Simpan gambar jika hasil sudah benar.'],['Apa yang harus ditempel?','Gunakan string Base64/Data URL yang valid.','Mengapa hasil bisa gagal?','Data yang tidak lengkap atau format Base64 yang tidak valid dapat menyebabkan kegagalan.']],
'csv-to-json': ['CSV ke JSON Online Gratis','Konversi data CSV sederhana menjadi JSON untuk membantu pekerjaan data dan pengembangan aplikasi.',['Tempel CSV pada kolom input.','Pastikan baris pertama berisi nama kolom.','Jalankan konversi dan salin JSON.'],['Apakah CSV kompleks didukung?','Tool ini ditujukan untuk CSV sederhana dengan pemisah koma.','Apa fungsi baris pertama?','Baris pertama digunakan sebagai nama properti JSON.']],
'json-to-csv': ['JSON ke CSV Online Gratis','Ubah array JSON menjadi CSV yang mudah dibuka atau diproses dalam spreadsheet.',['Tempel array JSON yang valid.','Jalankan konversi.','Salin CSV hasilnya.'],['Format JSON seperti apa?','Gunakan array berisi object JSON.','Apa jika properti antar object berbeda?','Tool menggabungkan nama properti yang ditemukan menjadi kolom CSV.']],
'xml-formatter': ['XML Formatter Online Gratis','Rapikan XML agar struktur tag lebih mudah dibaca dan diperiksa saat mengembangkan aplikasi.',['Tempel XML.','Klik tombol format.','Periksa struktur hasil.'],['Apakah XML diubah datanya?','Tool hanya memecah struktur tag untuk membantu keterbacaan.','Apakah cocok untuk debugging?','Ya, terutama untuk membaca XML yang ditulis dalam satu baris.']],
'html-formatter': ['HTML Formatter Online Gratis','Rapikan HTML sederhana agar struktur tag lebih mudah dibaca ketika mengedit atau memeriksa kode.',['Tempel HTML.','Klik format.','Salin hasil yang sudah dirapikan.'],['Apakah formatter memperbaiki semua kesalahan HTML?','Tidak, tool ini terutama membantu keterbacaan struktur tag.','Apakah kode asli aman?','Input diproses di browser.']],
'css-minifier': ['CSS Minifier Online Gratis','Minimalkan whitespace dan komentar CSS sederhana untuk membantu membuat kode stylesheet lebih ringkas.',['Tempel CSS.','Klik minify.','Salin hasil CSS.'],['Apakah semua CSS dijamin aman diminify?','Tool ini memakai aturan minifikasi sederhana, jadi uji hasil pada project sebelum dipakai produksi.','Apa manfaat minifikasi?','Kode dapat menjadi lebih ringkas dan mudah dikirim sebagai aset.']],
'js-minifier': ['JavaScript Minifier Online Gratis','Ringkas JavaScript sederhana dengan menghapus komentar dan whitespace yang tidak diperlukan.',['Tempel JavaScript.','Klik minify.','Uji hasil sebelum digunakan.'],['Apakah ini minifier JavaScript lengkap?','Tidak, ini minifier ringan berbasis aturan sederhana.','Perlukah menguji hasil?','Ya, selalu uji JavaScript setelah proses minifikasi.']],
'html-encoder': ['HTML Encoder Online Gratis','Encode karakter khusus HTML agar teks dapat ditampilkan sebagai teks literal tanpa dianggap sebagai tag.',['Tempel teks atau HTML.','Klik encode.','Salin hasil.'],['Apa yang di-encode?','Karakter khusus seperti ampersand, tanda kurung sudut, dan tanda kutip diubah menjadi entity HTML.','Kapan berguna?','Saat menampilkan contoh kode atau teks HTML sebagai konten.']],
'html-decoder': ['HTML Decoder Online Gratis','Kembalikan HTML entity menjadi karakter aslinya agar teks lebih mudah dibaca atau diproses.',['Tempel teks encoded.','Klik decode.','Salin hasilnya.'],['Apa itu HTML entity?','Entity adalah bentuk representasi karakter khusus dalam HTML.','Apakah script akan dijalankan?','Hasil ditampilkan sebagai teks, bukan dieksekusi sebagai HTML.']],
'uuid-generator': ['UUID Generator Online Gratis','Buat UUID secara cepat untuk ID unik pada aplikasi, database, pengujian, atau kebutuhan development.',['Masukkan jumlah UUID jika tersedia.','Klik generate.','Salin UUID yang diperlukan.'],['Apakah UUID benar-benar unik?','UUID dirancang dengan ruang kemungkinan yang sangat besar, tetapi tidak ada jaminan matematis absolut.','Bisa dipakai untuk database?','Ya, UUID umum digunakan sebagai identifier.']],
'slug-generator': ['URL Slug Generator Online Gratis','Buat slug URL yang bersih dari judul atau teks dengan huruf kecil dan tanda hubung.',['Masukkan judul.','Jalankan generator.','Salin slug untuk URL.'],['Apa itu slug?','Slug adalah bagian teks ramah URL yang biasanya mewakili judul halaman.','Mengapa memakai tanda hubung?','Tanda hubung membantu memisahkan kata agar URL mudah dibaca.']],
'lorem-ipsum': ['Lorem Ipsum Generator Online Gratis','Buat teks placeholder untuk mockup desain, layout website, dan pengujian tampilan.',['Tentukan jumlah paragraf.','Klik generate.','Salin teks placeholder.'],['Apakah Lorem Ipsum adalah konten final?','Tidak, Lorem Ipsum hanya teks sementara.','Kapan sebaiknya digunakan?','Saat desain membutuhkan isi sementara sebelum konten final tersedia.']],
'remove-duplicate-lines': ['Remove Duplicate Lines Online Gratis','Hapus baris teks yang sama dari daftar agar data lebih bersih dan tidak berulang.',['Tempel daftar teks.','Jalankan pembersihan.','Salin daftar tanpa duplikat.'],['Apakah urutan baris dipertahankan?','Ya, kemunculan pertama setiap baris dipertahankan.','Apa yang dianggap sama?','Baris dibandingkan berdasarkan teksnya.']],
'sort-lines': ['Sort Lines Online Gratis','Urutkan daftar teks berdasarkan abjad untuk membantu membersihkan daftar kata, nama, atau data sederhana.',['Tempel satu item per baris.','Klik sort.','Salin hasilnya.'],['Apakah baris kosong dipertahankan?','Baris kosong diabaikan.','Urutan seperti apa yang digunakan?','Tool menggunakan perbandingan teks bawaan browser.']],
'text-cleaner': ['Text Cleaner Online Gratis','Bersihkan teks dengan menghapus spasi berlebih, merapikan tiap baris, dan membuang baris kosong.',['Tempel teks.','Jalankan pembersihan.','Salin teks yang sudah bersih.'],['Apa yang dibersihkan?','Spasi berlebih dan baris kosong dibersihkan.','Apakah isi kata berubah?','Tool tidak sengaja mengubah kata, hanya whitespace.']],
'reading-time': ['Reading Time Calculator Online Gratis','Perkirakan waktu membaca berdasarkan jumlah kata agar kamu dapat memahami panjang konten dengan cepat.',['Masukkan atau tempel teks.','Jalankan kalkulator.','Lihat estimasi menit membaca.'],['Berapa kecepatan membaca yang dipakai?','Tool menggunakan asumsi sederhana sekitar 200 kata per menit.','Apakah hasilnya pasti?','Tidak, waktu nyata bergantung pada pembaca dan tingkat kesulitan teks.']],
'typing-speed-test': ['Typing Speed Test Online Gratis','Ukur kecepatan mengetik secara sederhana berdasarkan jumlah kata dan waktu yang dimasukkan.',['Masukkan teks atau data tes.','Masukkan durasi dalam detik jika tersedia.','Jalankan pengukuran WPM.'],['Apa itu WPM?','WPM berarti words per minute atau kata per menit.','Apakah ini tes mengetik lengkap?','Ini adalah pengukur sederhana, bukan platform tes mengetik lengkap.']],
'random-number-generator': ['Random Number Generator Online Gratis','Buat angka acak dalam rentang minimum dan maksimum yang kamu tentukan untuk permainan, pengujian, atau kebutuhan sehari-hari.',['Masukkan angka minimum.','Masukkan angka maksimum.','Klik Acak Angka.'],['Apakah angka maksimum bisa muncul?','Ya, rentang dibuat termasuk batas minimum dan maksimum.','Apakah hasilnya benar-benar acak?','Tool memakai generator acak bawaan browser untuk penggunaan umum.']],
'random-picker': ['Random Picker Online Gratis','Pilih satu item secara acak dari daftar nama, pilihan, atau data yang kamu masukkan.',['Masukkan satu pilihan per baris atau pisahkan dengan koma.','Klik tombol pilih.','Gunakan hasil yang terpilih.'],['Berapa item yang bisa dipilih?','Tool dapat memilih dari daftar yang dimasukkan ke input.','Apakah pilihan dibuat berulang?','Setiap klik memilih ulang secara acak.']],
'color-picker': ['Color Picker Online Gratis','Pilih warna dengan mudah untuk kebutuhan desain website, grafis, dan pembuatan konten.',['Pilih warna.','Lihat nilai warna yang tersedia.','Salin kode yang dibutuhkan.'],['Apa fungsi color picker?','Untuk memilih dan mendapatkan nilai warna secara praktis.','Bisa dipakai untuk website?','Ya, nilai warna dapat digunakan dalam CSS dan desain.']],
'hex-to-rgb': ['HEX ke RGB Converter Online Gratis','Konversi kode warna HEX menjadi nilai RGB untuk kebutuhan desain dan CSS.',['Masukkan kode HEX.','Jalankan konversi.','Salin nilai RGB.'],['Apa contoh kode HEX?','Contohnya #ff0000 untuk warna merah.','Apa bedanya HEX dan RGB?','Keduanya mewakili warna, tetapi menggunakan format nilai yang berbeda.']],
'rgb-to-hex': ['RGB ke HEX Converter Online Gratis','Konversi nilai RGB menjadi kode HEX yang praktis digunakan dalam CSS dan desain web.',['Masukkan nilai R,G,B.','Jalankan konversi.','Salin kode HEX.'],['Berapa rentang RGB?','Umumnya setiap kanal RGB berada pada 0 sampai 255.','Untuk apa HEX?','HEX sering digunakan dalam CSS dan tools desain.']],
'length-converter': ['Length Converter Online Gratis','Konversi nilai panjang dengan cepat untuk kebutuhan kerja, sekolah, desain, dan perhitungan sederhana.',['Masukkan nilai panjang.','Masukkan faktor konversi sesuai tampilan tool.','Lihat hasil konversi.'],['Apakah hasilnya untuk semua satuan?','Tool ini menyediakan konversi sederhana sesuai input yang tersedia.','Perlukah memeriksa satuan?','Ya, pastikan satuan sumber dan tujuan benar sebelum memakai hasil.']],
'weight-converter': ['Weight Converter Online Gratis','Bantu mengonversi nilai berat untuk kebutuhan sehari-hari, resep, pengiriman, atau perhitungan sederhana.',['Masukkan nilai berat.','Masukkan faktor konversi.','Gunakan hasilnya.'],['Apakah hasilnya selalu presisi?','Hasil mengikuti faktor yang digunakan oleh tool.','Apa yang perlu diperhatikan?','Periksa satuan sumber dan tujuan agar tidak salah interpretasi.']],
'temperature-converter': ['Temperature Converter Online Gratis','Konversi suhu antara Celsius, Fahrenheit, dan Kelvin dengan cepat.',['Masukkan nilai suhu.','Pilih arah konversi.','Lihat hasilnya.'],['Apakah rumus konversinya standar?','Tool menggunakan rumus konversi suhu umum.','Bisa untuk suhu negatif?','Ya, nilai negatif dapat diproses selama input valid.']],
'time-duration-calculator': ['Time Duration Calculator Online Gratis','Hitung selisih durasi antara dua waktu untuk membantu pencatatan kerja dan aktivitas harian.',['Masukkan waktu awal.','Masukkan waktu akhir.','Jalankan kalkulator.'],['Apa yang dihitung?','Tool menghitung selisih waktu dalam jam dan menit.','Bagaimana jika waktu akhir lebih kecil?','Selisih dihitung sebagai durasi absolut.']],
'date-calculator': ['Date Calculator Online Gratis','Tambahkan atau kurangi jumlah hari dari sebuah tanggal untuk mendapatkan tanggal baru.',['Masukkan tanggal.','Masukkan jumlah hari.','Lihat tanggal hasil.'],['Bisa mengurangi hari?','Ya, gunakan angka hari negatif jika input mendukungnya.','Apakah tahun kabisat diperhitungkan?','Perhitungan tanggal menggunakan objek Date pada browser.']],
'countdown-timer': ['Countdown Timer Online Gratis','Gunakan penghitung mundur sederhana untuk belajar, olahraga, presentasi, memasak, atau fokus kerja.',['Masukkan durasi detik.','Klik mulai.','Tunggu sampai hitungan selesai.'],['Apakah timer berjalan di browser?','Ya, penghitung berjalan pada halaman yang sedang dibuka.','Apakah halaman harus tetap terbuka?','Ya, jangan tutup halaman jika ingin melihat hitungan sampai selesai.']],
'stopwatch': ['Stopwatch Online Gratis','Ukur durasi aktivitas secara sederhana langsung di browser tanpa aplikasi tambahan.',['Klik mulai pada kontrol stopwatch.','Catat durasi yang tampil.','Hentikan atau mulai ulang sesuai kebutuhan.'],['Untuk apa stopwatch?','Untuk mengukur durasi aktivitas secara praktis.','Apakah cocok untuk pengukuran presisi tinggi?','Tidak; gunakan alat khusus untuk pengukuran yang membutuhkan presisi tinggi.']],
'loan-calculator': ['Loan Calculator Online Gratis','Hitung estimasi cicilan pinjaman bulanan berdasarkan pokok, bunga tahunan, dan tenor yang dimasukkan.',['Masukkan pokok pinjaman.','Masukkan bunga tahunan.','Masukkan tenor bulan lalu hitung.'],['Apakah hasilnya penawaran pinjaman?','Tidak, ini hanya kalkulasi estimasi berdasarkan input.','Apakah biaya lain dihitung?','Tidak kecuali dimasukkan sebagai bagian dari perhitungan tool.']],
'savings-calculator': ['Savings Calculator Online Gratis','Perkirakan nilai tabungan berdasarkan setoran, bunga, dan periode yang kamu masukkan.',['Masukkan nilai setoran.','Masukkan bunga.','Masukkan periode lalu hitung.'],['Apakah hasilnya jaminan keuntungan?','Tidak, hasil hanya estimasi matematis dari input.','Apakah biaya bank dihitung?','Tidak, kecuali dimasukkan dalam model perhitungan.']],
'tip-calculator': ['Tip Calculator Online Gratis','Hitung nominal tip dan total pembayaran berdasarkan harga dan persentase tip.',['Masukkan nilai tagihan.','Masukkan persentase tip.','Lihat tip dan total.'],['Bisa untuk membagi tagihan?','Tool ini menghitung tip dan total, bukan pembagian per orang.','Apakah persentase bisa diubah?','Ya, masukkan persentase yang kamu inginkan.']],
'tax-calculator': ['Tax Calculator Online Gratis','Hitung nilai pajak sederhana berdasarkan jumlah dasar dan persentase pajak yang dimasukkan.',['Masukkan nilai dasar.','Masukkan persentase pajak.','Lihat estimasi pajak.'],['Apakah ini kalkulator pajak resmi?','Tidak, ini kalkulator persentase sederhana dan bukan alat perpajakan resmi.','Apakah aturan pajak negara diperhitungkan?','Tidak; aturan khusus pajak perlu dicek pada sumber resmi.']],
'emi-calculator': ['EMI Calculator Online Gratis','Hitung estimasi cicilan berkala berdasarkan pokok, bunga, dan tenor menggunakan formula EMI sederhana.',['Masukkan pokok.','Masukkan bunga tahunan.','Masukkan tenor lalu hitung.'],['Apa itu EMI?','EMI adalah cicilan berkala yang dihitung dari pokok, bunga, dan tenor.','Apakah biaya tambahan dihitung?','Tidak, kecuali dimasukkan dalam perhitungan.']],
'compound-interest-calculator': ['Compound Interest Calculator Online Gratis','Hitung estimasi nilai akhir berdasarkan modal, tingkat bunga, dan periode dengan konsep bunga majemuk.',['Masukkan modal awal.','Masukkan tingkat bunga.','Masukkan periode lalu hitung.'],['Apa itu bunga majemuk?','Bunga majemuk menghitung pertumbuhan berdasarkan nilai yang telah bertambah dari periode sebelumnya.','Apakah hasilnya pasti terjadi?','Tidak, hasil adalah ilustrasi matematis berdasarkan asumsi input.']],
'simple-interest-calculator': ['Simple Interest Calculator Online Gratis','Hitung bunga sederhana dan total nilai berdasarkan modal, tingkat bunga, dan periode.',['Masukkan modal.','Masukkan tingkat bunga.','Masukkan periode lalu hitung.'],['Apa itu bunga sederhana?','Bunga sederhana dihitung dari modal awal berdasarkan tingkat dan periode.','Apakah cocok untuk semua produk keuangan?','Tidak; gunakan formula yang sesuai dengan produk atau perjanjian yang sebenarnya.']],
'profit-margin-calculator': ['Profit Margin Calculator Online Gratis','Hitung margin keuntungan berdasarkan biaya dan harga jual untuk membantu analisis harga produk.',['Masukkan biaya.','Masukkan harga jual.','Lihat persentase margin.'],['Apa itu profit margin?','Margin menunjukkan bagian keuntungan terhadap harga jual.','Apakah margin sama dengan markup?','Tidak. Margin memakai harga jual sebagai dasar, sedangkan markup memakai biaya sebagai dasar.']],
'markup-calculator': ['Markup Calculator Online Gratis','Hitung harga jual berdasarkan biaya dan persentase markup yang kamu tentukan.',['Masukkan biaya.','Masukkan persentase markup.','Lihat harga jual.'],['Apa itu markup?','Markup adalah tambahan persentase terhadap biaya untuk menentukan harga jual.','Apakah markup sama dengan margin?','Tidak, dasar perhitungannya berbeda.']],
'break-even-calculator': ['Break Even Calculator Online Gratis','Hitung perkiraan jumlah unit yang harus terjual agar pendapatan menutup biaya tetap berdasarkan input sederhana.',['Masukkan biaya tetap.','Masukkan harga per unit.','Masukkan biaya variabel per unit lalu hitung.'],['Apa itu break even point?','Titik impas adalah kondisi ketika pendapatan dan biaya berada pada titik yang sama.','Apakah biaya lain otomatis dihitung?','Tidak, hanya angka yang dimasukkan ke formula tool.']],
'percentage-change-calculator': ['Percentage Change Calculator Online Gratis','Hitung persentase perubahan dari nilai awal ke nilai akhir untuk analisis data sederhana.',['Masukkan nilai awal.','Masukkan nilai akhir.','Lihat persentase perubahan.'],['Apa arti hasil negatif?','Hasil negatif menunjukkan nilai akhir lebih rendah dari nilai awal.','Apakah ini perubahan relatif?','Ya, perhitungan memakai nilai awal sebagai dasar.']],
'invoice-generator': ['Invoice Generator Online Gratis','Buat format invoice sederhana dari informasi pelanggan dan nominal untuk kebutuhan pencatatan dasar.',['Masukkan nama pelanggan.','Masukkan nominal atau detail yang diperlukan.','Gunakan hasil dan cetak halaman bila diperlukan.'],['Apakah invoice ini dokumen pajak resmi?','Tidak, ini hanya template invoice sederhana.','Bisa dicetak?','Ya, hasil dapat dicetak menggunakan fitur print browser.']]
};

function addSEOContent() {
  const data = seo[t];
  const main = document.querySelector('main');
  if (!data || !main || document.getElementById('seo-content')) return;
  const [heading, intro, steps, faq] = data;
  const box = document.createElement('section');
  box.id = 'seo-content';
  box.style.cssText = 'margin-top:28px;background:#fff;padding:24px;border-radius:12px;line-height:1.7';
  box.innerHTML = `<h2>Tentang ${heading}</h2><p>${intro}</p><h2>Cara menggunakan</h2><ol>${steps.map(x=>`<li>${x}</li>`).join('')}</ol><h2>Pertanyaan umum</h2>${[0,2].map(i=>`<details style="margin:10px 0"><summary><strong>${faq[i]}</strong></summary><p>${faq[i+1]}</p></details>`).join('')}<p><a href="./popular-tools.html">Lihat 50 tools lainnya →</a></p>`;
  main.appendChild(box);
}

document.addEventListener('DOMContentLoaded', addSEOContent);
